//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendFaxConsole.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPPC_AutomatedFaxEntities1 : DbContext
    {
        public PPPC_AutomatedFaxEntities1()
            : base("name=PPPC_AutomatedFaxEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFaxRecipientMaster> tblFaxRecipientMasters { get; set; }
        public virtual DbSet<tblFaxRequestMaster> tblFaxRequestMasters { get; set; }
        public virtual DbSet<tblFaxRequestMaster_AUDIT> tblFaxRequestMaster_AUDIT { get; set; }
    }
}
