//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendFaxConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFaxRecipientMaster
    {
        public int ClientID { get; set; }
        public string Client_Name { get; set; }
        public string Client_Contact_Name { get; set; }
        public string Client_Fax_Number { get; set; }
        public string Client_Phone_Number { get; set; }
        public System.DateTime Audit_Date { get; set; }
        public System.DateTime Audit_Time { get; set; }
        public string Audit_User { get; set; }
    }
}
