//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendFaxConsole.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PPPC_AutomatedFaxEntities2 : DbContext
    {
        public PPPC_AutomatedFaxEntities2()
            : base("name=PPPC_AutomatedFaxEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFaxRecipientMaster> tblFaxRecipientMasters { get; set; }
        public virtual DbSet<tblFaxRequestMaster> tblFaxRequestMasters { get; set; }
        public virtual DbSet<tblFaxRequestMaster_AUDIT> tblFaxRequestMaster_AUDIT { get; set; }
    
        public virtual int lsp_DeleteFaxRequest(Nullable<int> faxRequestID)
        {
            var faxRequestIDParameter = faxRequestID.HasValue ?
                new ObjectParameter("FaxRequestID", faxRequestID) :
                new ObjectParameter("FaxRequestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lsp_DeleteFaxRequest", faxRequestIDParameter);
        }
    }
}
