//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendFaxConsole.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFaxRequestMaster
    {
        public int FaxRequestID { get; set; }
        public int ClientID { get; set; }
        public string Fax_File_Location { get; set; }
        public System.DateTime Date_Requested { get; set; }
        public Nullable<System.DateTime> Date_Last_Sent { get; set; }
    }
}
